---
- name: Display Role Details.
  debug:
    msg:
      - '===================================================================='
      - 'constrict0r.role'
      - 'Example Ansible Role.'
      - '===================================================================='
